### ISSUE TITLE
geodati.fmach.it non updated since november 30

### ISSUE THREAD

**Issue by dan980** [simone-f/wikipedia-tags-in-osm_italy-data#6]
Hi Simone,
the website for Italian wikipedia tags in Osm http://geodati.fmach.it/gfoss_geodata/osm/wtosm/it_IT/index.html is no longer updated since november 30 2016. 
Could you fix it? Thanks

**Comment by lucadelu** [comment]
There was a problem in the server, I fixed it and now it works correctly.
